auto-save-interval: 300

features:
  penalties: true
  bonuses: true
  feedback: true
  tool-reinforcement: true
  xp-transfer: true

xp-rates:
  mining.stone: 10
  mining.ore: 10
  farming.plant: 3
  farming.harvest: 5
  farming.till: 1
  farming.compost: 2
  farming.breed: 20
  combat.kill: 15
  building.basic: 2
  building.advanced: 2
  crafting.tool: 25
  crafting.armor: 30

penalty-thresholds:
  miner: 10.0
  farmer: 10.0
  guardsman: 10.0
  builder: 10.0
  blacksmith: 10.0

bonus-thresholds:
  miner: 50.0
  farmer: 50.0
  guardsman: 50.0
  builder: 50.0
  blacksmith: 50.0
