auto-save-interval: 300

# Advancement system configuration
advancement-grant-threshold: 0.01  # Grant advancements at 1% progress (0.01 = 1%, 1.0 = 100%)

features:
  penalties: true
  bonuses: true
  feedback: true
  tool-reinforcement: true
  xp-transfer: true
  dynamic-tree-generation: false  # Enable ML-based dynamic tree generation (experimental)

parent-xp:
  multiplier: 1.0  # Root gets 100% of XP first
  decay: 0.5       # Each child level gets 50% less (child gets 50%, grandchild gets 25%)

depth-xp-requirements:
  depth-1: 1000    # Root classes (farmer, miner, etc.)
  depth-2: 5000    # Categories (crop_farming, ore_mining, etc.)
  depth-3: 10000   # Specializations (wheat, diamond, etc.)
  depth-4: 15000   # Mastery (plant, harvest, strip_mining, etc.)

xp-rates:
  mining.stone: 10
  mining.ore: 10
  farming.plant: 3
  farming.harvest: 5
  farming.till: 1
  farming.compost: 2
  farming.breed: 20
  combat.kill: 15
  building.basic: 2
  building.advanced: 2
  crafting.tool: 25
  crafting.armor: 30

penalty-thresholds:
  miner: 10.0
  farmer: 10.0
  guardsman: 10.0
  builder: 10.0
  blacksmith: 10.0

bonus-thresholds:
  miner: 50.0
  farmer: 50.0
  guardsman: 50.0
  builder: 50.0
  blacksmith: 50.0
