storage:
  type: yaml
  auto-save-interval: 6000

specialization:
  max-efficiency: 3.5
  base-efficiency: 0.08
  experience-per-efficiency-point: 1000
  penalty-for-unspecialized: true
  allow-cross-specialization: true
  
  cognitive-capacity:
    enabled: true
    max-active-specializations: 4
    proficiency-threshold: 1.0
    mastery-threshold: 1.5
    interference-penalty: 0.15
    calculation-mode: "slot-based"

environmental-factors:
  enabled: true
  circumscription:
    enabled: true
    bonus: 0.2
    conflict-threshold: 0.6
    population-density-threshold: 0.8
  
  biome-productivity:
    plains: 1.5
    forest: 1.3
    jungle: 1.4
    desert: 0.6
    mountains: 0.7
    ocean: 0.8
    river: 1.2
    swamp: 1.1
    taiga: 0.9
    savanna: 1.0
  
  crop-growth:
    enabled: true
    apply-to-vanilla-crops: true
    
    crop-biome-affinity:
      wheat:
        optimal: [plains, river]
        good: [forest, savanna]
        poor: [desert, mountains]
        terrible: [ocean, swamp]
      
      carrots:
        optimal: [plains, forest]
        good: [taiga, river]
        poor: [desert, jungle]
        terrible: [ocean, mountains]
      
      potatoes:
        optimal: [plains, taiga]
        good: [forest, mountains]
        poor: [desert, savanna]
        terrible: [ocean, swamp]
      
      beetroots:
        optimal: [plains, forest]
        good: [taiga, mountains]
        poor: [desert, jungle]
        terrible: [ocean]
      
      melons:
        optimal: [jungle, swamp]
        good: [plains, forest]
        poor: [desert, taiga]
        terrible: [mountains, ocean]
      
      pumpkins:
        optimal: [plains, forest]
        good: [taiga, savanna]
        poor: [desert, jungle]
        terrible: [mountains, ocean]
      
      cocoa:
        optimal: [jungle]
        good: [swamp, forest]
        poor: [plains, savanna]
        terrible: [desert, mountains, taiga, ocean]
      
      sugar_cane:
        optimal: [river, swamp, jungle]
        good: [plains, forest]
        poor: [desert, savanna]
        terrible: [mountains, taiga, ocean]
    
    growth-multipliers:
      optimal: 1.5
      good: 1.2
      poor: 0.7
      terrible: 0.4
    
    food-surplus-bonus:
      enabled: true
      surplus-threshold: 1.3
      bonus-per-surplus: 0.1
      max-bonus: 0.3
  
  population-pressure:
    enabled: true
    density-penalty: 0.1
    density-threshold: 0.5
    max-penalty: 0.5
  
  resource-scarcity:
    enabled: true
    low-productivity-threshold: 0.8
    scarcity-multiplier: 0.5

social-systems:
  reputation:
    enabled: true
    notify-trades: false
    trade-cooldown-seconds: 5
    social-capital-formula:
      unique-partners-weight: 2.0
      total-trades-weight: 0.5
      max-bonus: 0.3
      bonus-multiplier: 0.05
    reciprocity:
      debt-threshold: 5
      gift-bond-strength: 0.5
      trade-bond-strength: 0.25
  
  collective-action:
    enabled: true
    free-rider-threshold: 0.3
    contribution-bonus-max: 0.2
    contribution-bonus-multiplier: 0.5
  
  political:
    enabled: true
    big-man-threshold: 10.0
    authority-thresholds:
      charismatic: 10.0
      traditional: 30.0
      rational-legal: 50.0
    legitimacy-values:
      charismatic: 0.5
      traditional: 0.7
      rational-legal: 0.9
    score-weights:
      social-capital: 0.4
      trading-partners: 0.3
      surplus: 0.3
    challenge:
      required-advantage: 1.2
      success-legitimacy-gain: 0.1
      redistribution-legitimacy-gain: 0.05
      max-legitimacy: 1.0
  
  skill-transfer:
    enabled: true
    transfer-rate: 0.3
    related-skills:
      mining:
        - mine_stone
        - mine_ores
        - mine_prismarine
        - mine_sandstone
      combat:
        - kill_hostile
        - kill_passive
      farming:
        - harvest_crops
        - breed_animals
      crafting:
        - craft_tools
        - craft_armor
        - smelt_items
      ocean:
        - catch_fish
        - collect_kelp
        - mine_prismarine
  
  variety-bonus:
    enabled: true
    bonus-per-different-action: 0.05
    max-variety-bonus: 0.5
    actions-required: 5
  
  mastery-bonus:
    enabled: true
    mastery-threshold: 2000
    bonus-per-1000-xp: 0.1
    max-mastery-bonus: 1.0
    exclusive-bonus: 0.2
  
  emergent-bonuses:
    speed-bonus:
      enabled: true
      applies-to: all
      min-experience: 0
    yield-bonus:
      enabled: true
      applies-to: breaking,gathering
      min-experience: 500
    durability-bonus:
      enabled: true
      applies-to: tool-using
      min-experience: 200
    quality-bonus:
      enabled: true
      applies-to: crafting,creation
      min-experience: 300
    efficiency-bonus:
      enabled: true
      applies-to: processing
      min-experience: 0
    discovery-bonus:
      enabled: true
      applies-to: interaction
      min-experience: 400
      rare-item-chance-multiplier: 1.0
      notification-sound: true
      enhanced-loot: true
  
actions:
  mine_stone:
    display-name: "Stone Mining"
    description: "Mining stone and related blocks"
    triggers:
      - type: BLOCK_BREAK
        materials:
          - STONE
          - COBBLESTONE
          - ANDESITE
          - DIORITE
          - GRANITE
          - DEEPSLATE
    experience: 1.0
    
  mine_ores:
    display-name: "Ore Mining"
    description: "Mining valuable ores"
    triggers:
      - type: BLOCK_BREAK
        materials:
          - COAL_ORE
          - IRON_ORE
          - GOLD_ORE
          - DIAMOND_ORE
          - EMERALD_ORE
          - LAPIS_ORE
          - REDSTONE_ORE
          - COPPER_ORE
          - DEEPSLATE_COAL_ORE
          - DEEPSLATE_IRON_ORE
          - DEEPSLATE_GOLD_ORE
          - DEEPSLATE_DIAMOND_ORE
          - DEEPSLATE_EMERALD_ORE
          - DEEPSLATE_LAPIS_ORE
          - DEEPSLATE_REDSTONE_ORE
          - DEEPSLATE_COPPER_ORE
    experience: 2.0
    
  harvest_crops:
    display-name: "Crop Harvesting"
    description: "Harvesting mature crops"
    triggers:
      - type: BLOCK_BREAK
        materials:
          - WHEAT
          - CARROTS
          - POTATOES
          - BEETROOTS
          - NETHER_WART
    experience: 1.0
    
  breed_animals:
    display-name: "Animal Breeding"
    description: "Breeding animals"
    triggers:
      - type: ENTITY_BREED
        entities:
          - COW
          - SHEEP
          - PIG
          - CHICKEN
          - RABBIT
          - HORSE
    experience: 3.0
    
  kill_hostile:
    display-name: "Combat"
    description: "Defeating hostile mobs"
    triggers:
      - type: ENTITY_DEATH
        entities:
          - ZOMBIE
          - SKELETON
          - CREEPER
          - SPIDER
          - ENDERMAN
          - WITCH
    experience: 2.0
    
  place_blocks:
    display-name: "Construction"
    description: "Placing building blocks"
    triggers:
      - type: BLOCK_PLACE
        materials: any
    experience: 0.5
    
  craft_tools:
    display-name: "Tool Crafting"
    description: "Crafting tools and weapons"
    triggers:
      - type: CRAFT_ITEM
        materials:
          - WOODEN_PICKAXE
          - STONE_PICKAXE
          - IRON_PICKAXE
          - DIAMOND_PICKAXE
          - NETHERITE_PICKAXE
          - WOODEN_AXE
          - STONE_AXE
          - IRON_AXE
          - DIAMOND_AXE
          - NETHERITE_AXE
          - WOODEN_SWORD
          - STONE_SWORD
          - IRON_SWORD
          - DIAMOND_SWORD
          - NETHERITE_SWORD
    experience: 2.0
    
  smelt_items:
    display-name: "Smelting"
    description: "Smelting items in furnaces"
    triggers:
      - type: FURNACE_EXTRACT
        materials: any
    experience: 1.0
    
  trade_villager:
    display-name: "Trading"
    description: "Trading with villagers"
    triggers:
      - type: VILLAGER_TRADE
    experience: 2.0
    
  enchant_item:
    display-name: "Enchanting"
    description: "Enchanting items"
    triggers:
      - type: ENCHANT_ITEM
    experience: 3.0
    
  catch_fish:
    display-name: "Fishing"
    description: "Catching fish"
    triggers:
      - type: FISH_CATCH
    experience: 1.5
    
  collect_kelp:
    display-name: "Kelp Harvesting"
    description: "Harvesting kelp and seagrass"
    triggers:
      - type: BLOCK_BREAK
        materials:
          - KELP
          - KELP_PLANT
          - SEAGRASS
          - TALL_SEAGRASS
    experience: 0.5
    
  mine_prismarine:
    display-name: "Ocean Monument Farming"
    description: "Mining prismarine and ocean materials"
    triggers:
      - type: BLOCK_BREAK
        materials:
          - PRISMARINE
          - PRISMARINE_BRICKS
          - DARK_PRISMARINE
          - SEA_LANTERN
    experience: 2.0


milestones:
  novice_miner:
    display-name: "&7Novice Miner"
    description: "Started your mining journey"
    requirements:
      actions:
        mine_stone: 100
    rewards:
      - type: MESSAGE
        value: "&aYou've become a Novice Miner!"
      - type: TITLE
        value: "&7Novice Miner"
        
  expert_miner:
    display-name: "&bExpert Miner"
    description: "Mastered the art of mining"
    requirements:
      actions:
        mine_stone: 1000
        mine_ores: 500
    rewards:
      - type: MESSAGE
        value: "&aYou've become an Expert Miner!"
      - type: TITLE
        value: "&bExpert Miner"
      - type: EFFECT
        value: "HASTE:1:permanent"
        
  master_blacksmith:
    display-name: "&6Master Blacksmith"
    description: "Mastered crafting and smelting"
    requirements:
      actions:
        craft_tools: 500
        smelt_items: 1000
    rewards:
      - type: MESSAGE
        value: "&aYou've become a Master Blacksmith!"
      - type: TITLE
        value: "&6Master Blacksmith"

multipliers:
  group_bonus:
    enabled: true
    radius: 10
    per-player: 0.1
    max-players: 5
    
  tool_bonus:
    enabled: true
    correct-tool: 1.2
    enchanted-tool: 1.5

display:
  action-bar-updates: true
  milestone-titles: false
  experience-format: "{action}: {experience} XP"
  show-efficiency-in-stats: true
  
performance:
  cache-player-data: true
  batch-writes: true
  max-tracked-actions: 0

crafting-projects:
  enabled: true
  base-success-chance: 0.5
  efficiency-success-bonus: 0.1
  max-success-chance: 0.95
  consumption-time-ticks: 32
  fallback-action-id: "craft_tools"
  
  # Food properties for the consumable crafting project
  food:
    base-nutrition: 2  # Base hunger points restored
    nutrition-per-component: 0.5  # Additional hunger per crafting component
    saturation: 0.5  # Saturation value
    can-always-eat: true  # Can eat even when full
  
  convertible-materials:
    # Tools
    - WOODEN_PICKAXE
    - STONE_PICKAXE
    - IRON_PICKAXE
    - GOLDEN_PICKAXE
    - DIAMOND_PICKAXE
    - NETHERITE_PICKAXE
    - WOODEN_AXE
    - STONE_AXE
    - IRON_AXE
    - GOLDEN_AXE
    - DIAMOND_AXE
    - NETHERITE_AXE
    - WOODEN_SHOVEL
    - STONE_SHOVEL
    - IRON_SHOVEL
    - GOLDEN_SHOVEL
    - DIAMOND_SHOVEL
    - NETHERITE_SHOVEL
    - WOODEN_HOE
    - STONE_HOE
    - IRON_HOE
    - GOLDEN_HOE
    - DIAMOND_HOE
    - NETHERITE_HOE
    
    # Weapons
    - WOODEN_SWORD
    - STONE_SWORD
    - IRON_SWORD
    - GOLDEN_SWORD
    - DIAMOND_SWORD
    - NETHERITE_SWORD
    - BOW
    - CROSSBOW
    - TRIDENT
    - SHIELD
    
    # Armor
    - LEATHER_HELMET
    - LEATHER_CHESTPLATE
    - LEATHER_LEGGINGS
    - LEATHER_BOOTS
    - CHAINMAIL_HELMET
    - CHAINMAIL_CHESTPLATE
    - CHAINMAIL_LEGGINGS
    - CHAINMAIL_BOOTS
    - IRON_HELMET
    - IRON_CHESTPLATE
    - IRON_LEGGINGS
    - IRON_BOOTS
    - GOLDEN_HELMET
    - GOLDEN_CHESTPLATE
    - GOLDEN_LEGGINGS
    - GOLDEN_BOOTS
    - DIAMOND_HELMET
    - DIAMOND_CHESTPLATE
    - DIAMOND_LEGGINGS
    - DIAMOND_BOOTS
    - NETHERITE_HELMET
    - NETHERITE_CHESTPLATE
    - NETHERITE_LEGGINGS
    - NETHERITE_BOOTS
    
    # Transportation
    - MINECART
    - CHEST_MINECART
    - FURNACE_MINECART
    - HOPPER_MINECART
    - TNT_MINECART
    - OAK_BOAT
    - SPRUCE_BOAT
    - BIRCH_BOAT
    - JUNGLE_BOAT
    - ACACIA_BOAT
    - DARK_OAK_BOAT
    - MANGROVE_BOAT
    - CHERRY_BOAT
    - BAMBOO_RAFT
    
    # Redstone & Mechanisms
    - PISTON
    - STICKY_PISTON
    - DISPENSER
    - DROPPER
    - HOPPER
    - OBSERVER
    - REPEATER
    - COMPARATOR
    - REDSTONE_LAMP
    - NOTE_BLOCK
    - JUKEBOX
    - LEVER
    - TRIPWIRE_HOOK
    
    # Utility Blocks
    - CRAFTING_TABLE
    - FURNACE
    - BLAST_FURNACE
    - SMOKER
    - ANVIL
    - ENCHANTING_TABLE
    - BREWING_STAND
    - CAULDRON
    - CHEST
    - BARREL
    - SHULKER_BOX
    - ENDER_CHEST
    - BOOKSHELF
    - LECTERN
    - COMPOSTER
    - LOOM
    - STONECUTTER
    - SMITHING_TABLE
    - GRINDSTONE
    - CARTOGRAPHY_TABLE
    - FLETCHING_TABLE
    - BEEHIVE
    - LIGHTNING_ROD
    
    # Decorative Blocks
    - BEACON
    - CONDUIT
    - LANTERN
    - SOUL_LANTERN
    - TORCH
    - SOUL_TORCH
    - CAMPFIRE
    - SOUL_CAMPFIRE
    - LADDER
    - SCAFFOLDING
    - ARMOR_STAND
    - ITEM_FRAME
    - GLOW_ITEM_FRAME
    - PAINTING
    - FLOWER_POT
    - BANNER
    - BELL
    
    # Food & Consumables
    - BREAD
    - COOKIE
    - CAKE
    - PUMPKIN_PIE
    - MUSHROOM_STEW
    - RABBIT_STEW
    - BEETROOT_SOUP
    - SUSPICIOUS_STEW
    - GOLDEN_APPLE
    - GOLDEN_CARROT
    
    # Utility Items
    - BUCKET
    - WATER_BUCKET
    - LAVA_BUCKET
    - MILK_BUCKET
    - POWDER_SNOW_BUCKET
    - FISHING_ROD
    - FLINT_AND_STEEL
    - SHEARS
    - COMPASS
    - CLOCK
    - SPYGLASS
    - MAP
    - LEAD
    - NAME_TAG
    - SADDLE
    - BRUSH
    
    # Building Blocks
    - IRON_BARS
    - CHAIN
    - IRON_DOOR
    - IRON_TRAPDOOR
    - GLASS_PANE
    - BRICK
    - NETHER_BRICK
    - QUARTZ_BLOCK
    - PURPUR_BLOCK
    - PRISMARINE
    - PRISMARINE_BRICKS
    - DARK_PRISMARINE
    - SEA_LANTERN

debug:
  enabled: false
  log-actions: false
  log-restrictions: false
